version: "3"
services:
  web:
    image: openresty/openresty:1.25.3.1-2-alpine-fat
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./web:/usr/local/openresty/nginx/html/sso/
    ports:
      - "80:80"
  dremio:
    image: dremio/dremio-oss:24.3.2
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
